version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - home-library-network
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - home-library-network
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
  workflow:
    container_name: workflow
    build:
      context: ./workflow
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${WORKFLOW_PORT}:${WORKFLOW_PORT}
    depends_on:
      - postgres
    networks:
      - home-library-network
    volumes:
      - ./workflow:/usr/src/app/workflow
      - /usr/src/app/workflow/node_modules

  postgres:
    build:
      context: .
      dockerfile: ./backend/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - home-library-network
    volumes:
      - ./backend/docker/db/data:/var/lib/postgresql/data/
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - "3000:3000"
    networks:
      - home-library-network
    depends_on:
      - postgres
networks:
  home-library-network:
    driver: bridge
